import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
	const contenttree = [
		// /health
		'/health',

		// /health/dental
		'/health/dental',

		// /health/dental/home
		'/health/dental/home',
		'/health/dental/home/fancybox',
		'/health/dental/home/fancybox/fancybox-neu',
		'/health/dental/home/fancybox/urlaub',
		'/health/dental/home/infobox',
		'/health/dental/home/themenbox',

		// /health/dental/kontakt
		'/health/dental/kontakt',
		'/health/dental/kontakt/datenschutz',
		'/health/dental/kontakt/datenschutzerklaerung',
		'/health/dental/kontakt/erster_besuch',
		'/health/dental/kontakt/impressum',
		'/health/dental/kontakt/maps',
		'/health/dental/kontakt/onlineterminanfrage',
		'/health/dental/kontakt/sprechzeiten',
		'/health/dental/kontakt/vor_dem_termin',
		'/health/dental/kontakt/wunschterminkalender',

		// /health/dental/praxis
		'/health/dental/praxis',
		'/health/dental/praxis/aerzte',
		'/health/dental/praxis/ausstattung',
		'/health/dental/praxis/behandlungskonzept',
		'/health/dental/praxis/bildergalerie',
		'/health/dental/praxis/dentallabor',
		'/health/dental/praxis/microsites',
		'/health/dental/praxis/microsites/dentalhygienikerin',
		'/health/dental/praxis/microsites/dgi_curriculum_implantologie_',
		'/health/dental/praxis/microsites/kieferorthopaedie',
		'/health/dental/praxis/microsites/mom',
		'/health/dental/praxis/microsites/msc_kfo',
		'/health/dental/praxis/microsites/msc',
		'/health/dental/praxis/microsites/oralchirurgie',
		'/health/dental/praxis/microsites/prophylaxeassistentin',
		'/health/dental/praxis/microsites/taetigkeitsschwerpunkt',
		'/health/dental/praxis/philosophie',
		'/health/dental/praxis/team',
		'/health/dental/praxis/technik',
		"/health/dental/praxis/technik/3d-navigation",
		"/health/dental/praxis/technik/3d-planung",
		"/health/dental/praxis/technik/abdruck-modellscanner",
		"/health/dental/praxis/technik/air-flow-master",
		"/health/dental/praxis/technik/air-flow-master-piezon",
		"/health/dental/praxis/technik/air-flow-technik",
		"/health/dental/praxis/technik/air-scaler",
		"/health/dental/praxis/technik/arcus-digma",
		"/health/dental/praxis/technik/backward_planning",
		"/health/dental/praxis/technik/cad-cam-zahnersatz",
		"/health/dental/praxis/technik/cadiax",
		"/health/dental/praxis/technik/cercon",
		"/health/dental/praxis/technik/cerec-3d",
		"/health/dental/praxis/technik/cerec-inlab",
		"/health/dental/praxis/technik/diagnocam",
		"/health/dental/praxis/technik/diagnodent",
		"/health/dental/praxis/technik/digitale_zahnfarbenbestimmung",
		"/health/dental/praxis/technik/digitale-volumentomographie",
		"/health/dental/praxis/technik/digitales-roentgen",
		"/health/dental/praxis/technik/dir-system",
		"/health/dental/praxis/technik/elektrisches-laengenmessgeraet",
		"/health/dental/praxis/technik/elektrotom",
		"/health/dental/praxis/technik/florida-probe",
		"/health/dental/praxis/technik/freecorder-blue-fox",
		"/health/dental/praxis/technik/hardlaser",
		"/health/dental/praxis/technik/hydrokolloid-abformungen",
		"/health/dental/praxis/technik/icon",
		"/health/dental/praxis/technik/intraorale-kamera",
		"/health/dental/praxis/technik/intraoralscanner",
		"/health/dental/praxis/technik/ipr",
		"/health/dental/praxis/technik/jeder-system",
		"/health/dental/praxis/technik/karies_indikator",
		"/health/dental/praxis/technik/kofferdam",
		"/health/dental/praxis/technik/laserbehandlung",
		"/health/dental/praxis/technik/lupenbrille",
		"/health/dental/praxis/technik/maschinelle-wurzelkanalbehandlung",
		"/health/dental/praxis/technik/op-mikroskop-allgemein",
		"/health/dental/praxis/technik/op-mikroskop-wurzelkanalbehandlung",
		"/health/dental/praxis/technik/oral-health-manager",
		"/health/dental/praxis/technik/ozonbehandlung",
		"/health/dental/praxis/technik/perio-marker",
		"/health/dental/praxis/technik/periochip",
		"/health/dental/praxis/technik/perioscan",
		"/health/dental/praxis/technik/periotest",
		"/health/dental/praxis/technik/photoaktivierte-oraldesinfektion",
		"/health/dental/praxis/technik/photodynamische-lasertherapie",
		"/health/dental/praxis/technik/photothermische-therapie",
		"/health/dental/praxis/technik/piezosurgery",
		"/health/dental/praxis/technik/piezotom",
		"/health/dental/praxis/technik/prognos-meridiandiagnostik",
		"/health/dental/praxis/technik/pulverstrahlgeraet",
		"/health/dental/praxis/technik/pulverstrahlgeraet-paro",
		"/health/dental/praxis/technik/siroinspect",
		"/health/dental/praxis/technik/softlaser",
		"/health/dental/praxis/technik/sonicweld-rx",
		"/health/dental/praxis/technik/sonosurgery",
		"/health/dental/praxis/technik/soprolife",
		"/health/dental/praxis/technik/spectroshade",
		"/health/dental/praxis/technik/the-wand",
		"/health/dental/praxis/technik/thermoplastische-fuellungen",
		"/health/dental/praxis/technik/trinkwasseraufbereitung",
		"/health/dental/praxis/technik/ultraschall-chirurgie",
		"/health/dental/praxis/technik/ultraschall-paro",
		"/health/dental/praxis/technik/ultraschallaktivierte-spuelloesungen",
		"/health/dental/praxis/technik/vistacam",
		"/health/dental/praxis/technik/zebris-jma-system",
		'/health/dental/praxis/termine',
		'/health/dental/praxis/verbaende',
		'/health/dental/praxis/verbaende/aap',
		'/health/dental/praxis/verbaende/aefz',
		'/health/dental/praxis/verbaende/aget',
		'/health/dental/praxis/verbaende/akademie_fuer_akupunktur_und_aurikulo_medizin',
		'/health/dental/praxis/verbaende/apw',
		'/health/dental/praxis/verbaende/aroe',
		'/health/dental/praxis/verbaende/bdiz',
		'/health/dental/praxis/verbaende/bdo',
		'/health/dental/praxis/verbaende/bergische',
		'/health/dental/praxis/verbaende/bfsp',
		'/health/dental/praxis/verbaende/bnz',
		'/health/dental/praxis/verbaende/cochranelibrary',
		'/health/dental/praxis/verbaende/daegfa',
		'/health/dental/praxis/verbaende/dagz',
		'/health/dental/praxis/verbaende/dgaepc',
		'/health/dental/praxis/verbaende/dgaez',
		'/health/dental/praxis/verbaende/dgao',
		'/health/dental/praxis/verbaende/dgbt',
		'/health/dental/praxis/verbaende/dgcz',
		'/health/dental/praxis/verbaende/dgendo',
		'/health/dental/praxis/verbaende/dget',
		'/health/dental/praxis/verbaende/dgfan',
		'/health/dental/praxis/verbaende/dgfdt',
		'/health/dental/praxis/verbaende/dgi',
		'/health/dental/praxis/verbaende/dgk',
		'/health/dental/praxis/verbaende/dgkfo',
		'/health/dental/praxis/verbaende/dgkz',
		'/health/dental/praxis/verbaende/dgl',
		'/health/dental/praxis/verbaende/dgmkg',
		'/health/dental/praxis/verbaende/dgoi',
		'/health/dental/praxis/verbaende/dgp',
		'/health/dental/praxis/verbaende/dgpro',
		'/health/dental/praxis/verbaende/dgqz',
		'/health/dental/praxis/verbaende/dgz',
		'/health/dental/praxis/verbaende/dgzh',
		'/health/dental/praxis/verbaende/dgzi',
		'/health/dental/praxis/verbaende/dgzmk',
		'/health/dental/praxis/verbaende/dgzs',
		'/health/dental/praxis/verbaende/diz',
		'/health/dental/praxis/verbaende/dn',
		'/health/dental/praxis/verbaende/dnebm',
		'/health/dental/praxis/verbaende/dzv',
		'/health/dental/praxis/verbaende/eao',
		'/health/dental/praxis/verbaende/ecdi',
		'/health/dental/praxis/verbaende/fdi',
		'/health/dental/praxis/verbaende/fvdz',
		'/health/dental/praxis/verbaende/gzm',
		'/health/dental/praxis/verbaende/hartmannbund',
		'/health/dental/praxis/verbaende/hypnose',
		'/health/dental/praxis/verbaende/icoi',
		'/health/dental/praxis/verbaende/igumed',
		'/health/dental/praxis/verbaende/ihcf',
		'/health/dental/praxis/verbaende/imc',
		'/health/dental/praxis/verbaende/iti',
		'/health/dental/praxis/verbaende/leading_medicine_germany',
		'/health/dental/praxis/verbaende/master_of_science_in_oral_implantology',
		'/health/dental/praxis/verbaende/meg',
		'/health/dental/praxis/verbaende/nagp',
		'/health/dental/praxis/verbaende/neue_gruppe',
		'/health/dental/praxis/verbaende/ssc',
		'/health/dental/praxis/verbaende/steinbeis_hochschule',
		'/health/dental/praxis/verbaende/studiengruppe_fuer_restaurative_zahnheilkunde',
		'/health/dental/praxis/verbaende/vdze',
		'/health/dental/praxis/verbaende/wehrpharmazie',
		'/health/dental/praxis/verbaende/wgzmk',
		'/health/dental/praxis/verbaende/zibs',

		// /health/dental/seo
		"/health/dental/seo",

		// /health/dental/service
		"/health/dental/service",
		"/health/dental/service/checkliste",
		"/health/dental/service/checkliste_termin",
		"/health/dental/service/checkliste_ueberweiser",
		"/health/dental/service/downloads",
		"/health/dental/service/faq",
		"/health/dental/service/glossar-mkg",
		"/health/dental/service/kinderecke",
		"/health/dental/service/neupatienten",
		"/health/dental/service/notfall",
		"/health/dental/service/onlineterminanfrage",
		"/health/dental/service/serviceleistungen",
		"/health/dental/service/SOS",
		"/health/dental/service/SOS/sos_kurz_1",
		"/health/dental/service/SOS/sos_kurz_2",
		"/health/dental/service/SOS/sos_kurz_3",
		"/health/dental/service/SOS/sos_kurz_4",
		"/health/dental/service/SOS/sos_lang_1",
		"/health/dental/service/SOS/sos-bootstrap",
		"/health/dental/service/SOS/sos-mkg",
		"/health/dental/service/SOS/sos-standard",
		"/health/dental/service/tipps",
		"/health/dental/service/tipps/bleaching",
		"/health/dental/service/tipps/checkliste_urlaub",
		"/health/dental/service/tipps/implantate_pflegen",
		"/health/dental/service/tipps/kinderzahnpflege",
		"/health/dental/service/tipps/nach_implantation",
		"/health/dental/service/tipps/nach_op",
		"/health/dental/service/tipps/pflege_und_ernaehrung",
		"/health/dental/service/tipps/prothese_pflegen",
		"/health/dental/service/tipps/schwangerschaft",
		"/health/dental/service/tipps/vor_nach_op",
		"/health/dental/service/tipps/zahngesunde_ernaehrung",
		"/health/dental/service/tipps/zahntipps_festtage",
		"/health/dental/service/tipps/zahntipps-festtage",
		"/health/dental/service/winterzauber",
		"/health/dental/service/winterzauber/zahntipps",
		"/health/dental/service/winterzauber/zahntipps_lang",
		"/health/dental/service/wunschterminplaner",
	];

	const completions: vscode.QuickPickItem[] = [];

	contenttree.forEach((path: string) => {
		completions.push({
			label: path.split('/').pop(),
			detail: path
		});
	});

	// The command has been defined in the package.json file
	// Now provide the implementation of the command with registerCommand
	// The commandId parameter must match the command field in package.json
	let disposable = vscode.commands.registerCommand('extension.insertcontent', () => {
		let editor = vscode.window.activeTextEditor;

		vscode.window.showQuickPick(completions).then(pick => {
			editor.edit(edit => {
				editor.selections.forEach(selection => {
					edit.insert(
						selection.start,
						`<IEQ-CMS function="InsertContent" param="content=${pick.detail};kurzfassung=nein">InsertContent Langfassung - ${pick.label}</IEQ-CMS>`
					);
				});
			});
		});
	});

	context.subscriptions.push(disposable);
}

export function deactivate() {}
